name: RUN - DEPLOY

on:
  push: # también puedes usar merge, release...
    branches: [ "main", "develop" ] 

jobs:
  
   deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy')"
    strategy:
       matrix:
         node-version: [16]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i --location=global yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      # Sets the branch name as environment variable
      - uses: nelonoel/branch-name@v1.0.1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          working-directory: .next
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_ID }}
          github-comment: "Prod deploy v${{ github.ref }}"
          vercel-org-id: ${{ secrets.VERCEL_ORG }}
          

# read more in: https://docs.github.com/es/actions